version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "7000:7000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/image-moderation
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:7000
    ports:
      - "3000:80"

  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
